<?php

class IndexController extends Zend_Controller_Action
{

    public function init()
    {
        /* Initialize action controller here */
    }

    public function indexAction()
    {
    	require_once('LoggerManager.php');
    	$logger =& LoggerManager::getLogger('main');
    	
    	$logger->debug('this is a DEBUG log generated by main() function');
    	$logger->info('this is an INFO log generated by main() function');
    	$logger->warn('this is a WARN log generated by main() function');
    	$logger->error('this is an ERROR log generated by main() function');
    	$logger->fatal('this is a FATAL log generated by main() function');
    	
    	 
    }


}

